### ISSUE TITLE
ReferenceError: Headers is not defined

### ISSUE THREAD

**Issue by MonsieurBarti** [jpmonette/bscscan-ts#10]
This error happens everytime I try to request client.accounts.getBalance({ address: 'my-address'}). The error is the same for other requests.

My code is pretty straight forward : 
```js
const { BscScan } = require('@jpmonette/bscscan')
const client = new BscScan({ apikey: process.env.BSC_API_KEY })
module.exports = async req => {
	try {
		let request = await client.accounts.getBalance({ address: req.query.address })
		return request.result
	} catch (error) {
		throw error
	}
}
```

**Comment by richgoldmd** [comment]
You can solve this by making sure you have a fetch compatible library installed and loaded.
If you are using node,

```bash
yarn add isomorphic-fetch
```

and in your ts file where you use the client, 
```ts
import "isomorphic-fetch";
```

**Comment by jpmonette** [comment]
@MonsieurBarti As @richgoldmd said above, `bscscan-ts` requires the Fetch API which is not packaged in Node.js out of the box. However, you can easily bring your own implementation using either `isomorphic-fetch`, `cross-fetch` or `node-fetch`.

Hopefully that solves your issue. If not, you can re-open the Issue.
